  <select name="country_code"  required>
                            <option value="+20" selected>Egypt (+20)</option>
                            <option value="+1">United States (+1)</option>
                            <option value="+1242">Bahamas (+1242)</option>
                            <option value="+1246">Barbados (+1246)</option>
                            <option value="+1264">Anguilla (+1264)</option>
                            <option value="+1268">Antigua and Barbuda (+1268)</option>
                            <option value="+1284">British Virgin Islands (+1284)</option>
                            <option value="+1340">U.S. Virgin Islands (+1340)</option>
                            <option value="+1441">Bermuda (+1441)</option>
                            <option value="+1473">Grenada (+1473)</option>
                            <option value="+1649">Turks and Caicos Islands (+1649)</option>
                            <option value="+1664">Montserrat (+1664)</option>
                            <option value="+1670">Northern Mariana Islands (+1670)</option>
                            <option value="+1684">American Samoa (+1684)</option>
                            <option value="+1758">Saint Lucia (+1758)</option>
                            <option value="+1767">Dominica (+1767)</option>
                            <option value="+1784">Saint Vincent and the Grenadines (+1784)</option>
                            <option value="+1787">Puerto Rico (+1787)</option>
                            <option value="+1809">Dominican Republic (+1809)</option>
                            <option value="+1829">Dominican Republic (+1829)</option>
                            <option value="+1849">Dominican Republic (+1849)</option>
                            <option value="+1868">Trinidad and Tobago (+1868)</option>
                            <option value="+1869">Saint Kitts and Nevis (+1869)</option>
                            <option value="+1876">Jamaica (+1876)</option>
                            <option value="+211">South Sudan (+211)</option>
                            <option value="+212">Morocco (+212)</option>
                            <option value="+213">Algeria (+213)</option>
                            <option value="+216">Tunisia (+216)</option>
                            <option value="+218">Libya (+218)</option>
                            <option value="+220">Gambia (+220)</option>
                            <option value="+221">Senegal (+221)</option>
                            <option value="+222">Mauritania (+222)</option>
                            <option value="+223">Mali (+223)</option>
                            <option value="+224">Guinea (+224)</option>
                            <option value="+225">Côte d'Ivoire (+225)</option>
                            <option value="+226">Burkina Faso (+226)</option>
                            <option value="+227">Niger (+227)</option>
                            <option value="+228">Togo (+228)</option>
                            <option value="+229">Benin (+229)</option>
                            <option value="+230">Mauritius (+230)</option>
                            <option value="+231">Liberia (+231)</option>
                            <option value="+232">Sierra Leone (+232)</option>
                            <option value="+233">Ghana (+233)</option>
                            <option value="+234">Nigeria (+234)</option>
                            <option value="+235">Chad (+235)</option>
                            <option value="+236">Central African Republic (+236)</option>
                            <option value="+237">Cameroon (+237)</option>
                            <option value="+238">Cape Verde (+238)</option>
                            <option value="+239">Sao Tome and Principe (+239)</option>
                            <option value="+240">Equatorial Guinea (+240)</option>
                            <option value="+241">Gabon (+241)</option>
                            <option value="+242">Congo (+242)</option>
                            <option value="+243">DR Congo (+243)</option>
                            <option value="+244">Angola (+244)</option>
                            <option value="+245">Guinea-Bissau (+245)</option>
                            <option value="+246">British Indian Ocean Territory (+246)</option>
                            <option value="+248">Seychelles (+248)</option>
                            <option value="+249">Sudan (+249)</option>
                            <option value="+250">Rwanda (+250)</option>
                            <option value="+251">Ethiopia (+251)</option>
                            <option value="+252">Somalia (+252)</option>
                            <option value="+253">Djibouti (+253)</option>
                            <option value="+254">Kenya (+254)</option>
                            <option value="+255">Tanzania (+255)</option>
                            <option value="+256">Uganda (+256)</option>
                            <option value="+257">Burundi (+257)</option>
                            <option value="+258">Mozambique (+258)</option>
                            <option value="+260">Zambia (+260)</option>
                            <option value="+261">Madagascar (+261)</option>
                            <option value="+262">Réunion (+262)</option>
                            <option value="+263">Zimbabwe (+263)</option>
                            <option value="+264">Namibia (+264)</option>
                            <option value="+265">Malawi (+265)</option>
                            <option value="+266">Lesotho (+266)</option>
                            <option value="+267">Botswana (+267)</option>
                            <option value="+268">Eswatini (+268)</option>
                            <option value="+269">Comoros (+269)</option>
                            <option value="+27">South Africa (+27)</option>
                            <option value="+290">Saint Helena (+290)</option>
                            <option value="+291">Eritrea (+291)</option>
                            <option value="+297">Aruba (+297)</option>
                            <option value="+298">Faroe Islands (+298)</option>
                            <option value="+299">Greenland (+299)</option>
                            <option value="+30">Greece (+30)</option>
                            <option value="+31">Netherlands (+31)</option>
                            <option value="+32">Belgium (+32)</option>
                            <option value="+33">France (+33)</option>
                            <option value="+34">Spain (+34)</option>
                            <option value="+35">Europe Shared (+35)</option>
                            <option value="+36">Hungary (+36)</option>
                            <option value="+39">Italy (+39)</option>
                            <option value="+40">Romania (+40)</option>
                            <option value="+41">Switzerland (+41)</option>
                            <option value="+43">Austria (+43)</option>
                            <option value="+44">United Kingdom (+44)</option>
                            <option value="+45">Denmark (+45)</option>
                            <option value="+46">Sweden (+46)</option>
                            <option value="+47">Norway (+47)</option>
                            <option value="+48">Poland (+48)</option>
                            <option value="+49">Germany (+49)</option>
                            <option value="+51">Peru (+51)</option>
                            <option value="+52">Mexico (+52)</option>
                            <option value="+53">Cuba (+53)</option>
                            <option value="+54">Argentina (+54)</option>
                            <option value="+55">Brazil (+55)</option>
                            <option value="+56">Chile (+56)</option>
                            <option value="+57">Colombia (+57)</option>
                            <option value="+58">Venezuela (+58)</option>
                            <option value="+60">Malaysia (+60)</option>
                            <option value="+62">Indonesia (+62)</option>
                            <option value="+63">Philippines (+63)</option>
                            <option value="+64">New Zealand (+64)</option>
                            <option value="+65">Singapore (+65)</option>
                            <option value="+66">Thailand (+66)</option>
                            <option value="+81">Japan (+81)</option>
                            <option value="+82">Korea, South (+82)</option>
                            <option value="+84">Vietnam (+84)</option>
                            <option value="+86">China (+86)</option>
                            <option value="+90">Turkey (+90)</option>
                            <option value="+92">Pakistan (+92)</option>
                            <option value="+93">Afghanistan (+93)</option>
                            <option value="+94">Sri Lanka (+94)</option>
                            <option value="+95">Myanmar (+95)</option>
                            <option value="+98">Iran (+98)</option>
                        </select>